baseURL: /
languageCode: en-US
title: Daniel Vartanian
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug
params:
  author: Daniel Vartanian
  avatar: img/profile.png
  custom_css: []
  custom_js: []
  description: I'm **Daniel Vartanian**, a Bioinformatician at @gipso.
  social:
    Twitter: danielvartan
    Github: danielvartan
    Email: danvartan@gmail.com
